services:
  - type: web
    name: french-tutor
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python backend/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
