services:
  - type: web
    name: fr-ai-tutor
    runtime: python
    pythonVersion: 3.10.12
    plan: free
    region: frankfurt
    repo: https://github.com/wildc4rd23/FR-AI-Tutor.git
    autoDeploy: true

    buildCommand: |
      pip install -r requirements.txt

    # Verwende Gunicorn für Production
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"