services:
  - type: web
    name: fr-ai-tutor
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y libsndfile1 ffmpeg git-lfs
      git lfs install
      mkdir -p backend/models
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    build:
      pythonVersion: 3.10.12
    repo: https://github.com/wildc4rd23/FR-AI-Tutor.git
    autoDeploy: true