services:
  - type: web
    name: fr-ai-tutor
    runtime: python
    plan: free
    region: frankfurt

    repo: https://github.com/wildc4rd23/FR-AI-Tutor.git
    autoDeploy: true

    buildCommand: |
      apt-get update
      apt-get install -y libsndfile1 ffmpeg git-lfs
      git lfs install
      git lfs pull  # ⬅️ Wichtig: Lade .pth Modelldateien per Git LFS herunter
      pip install -r requirements.txt

    startCommand: python backend/app.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12